import clang.cindex as CX
from meta_info import AttributeParser, Namespace


class CodeGenerator:
    """Generates UDRefl registration code from parsed Clang AST nodes."""

    def __init__(self, attr_parser: AttributeParser):
        self._attr_parser = attr_parser
        self._classes = []

    def _parse_annotation(self, node: CX.Cursor) -> list:
        """Parse clang::annotate attributes from a cursor's children."""
        for child in node.get_children():
            if child.kind == CX.CursorKind.ANNOTATE_ATTR:
                return self._attr_parser.parse_attributes(child.spelling)
        return []

    def _has_attr(self, attrs: list, name: str) -> bool:
        return any(a.name() == name for a in attrs)

    def _get_tag(self, attrs: list, attr_name: str, tag_name: str, default: str = '') -> str:
        for a in attrs:
            if a.name() == attr_name and tag_name in a.tags():
                return a.tags()[tag_name]
        return default

    def add_class(self, node: CX.Cursor, namespace: Namespace):
        """Parse a class cursor and collect meta-annotated fields/methods."""
        class_name = node.spelling
        ns_name = namespace.identify_name()
        full_name = f"{ns_name}::{class_name}" if ns_name != '::' else class_name

        # Parse class-level annotation
        class_attrs = self._parse_annotation(node)
        if not self._has_attr(class_attrs, 'Meta'):
            return  # Only process classes marked with [[Meta()]]

        class_info = {
            'name': class_name,
            'namespace': ns_name,
            'full_name': full_name,
            'bases': [],
            'fields': [],
            'methods': [],
        }

        for child in node.get_children():
            if child.kind == CX.CursorKind.CXX_BASE_SPECIFIER:
                # Prefer TYPE_REF for non-template bases (gives fully qualified name).
                # For template bases like enable_shared_from_this<T>, child.spelling
                # already contains the full specialization text.
                base_name = child.spelling
                for grandchild in child.get_children():
                    if grandchild.kind == CX.CursorKind.TYPE_REF:
                        ref_name = grandchild.spelling.replace(
                            'class ', '').replace('struct ', '')
                        # If the base is a simple class (no template args) use TYPE_REF
                        # which has the fully qualified namespace.
                        if '<' not in base_name:
                            base_name = ref_name
                        break
                class_info['bases'].append(base_name)

            elif child.kind == CX.CursorKind.FIELD_DECL:
                attrs = self._parse_annotation(child)
                if self._has_attr(attrs, 'Property'):
                    ui_name = self._get_tag(
                        attrs, 'Property', 'UIName', child.spelling)
                    class_info['fields'].append({
                        'name': child.spelling,
                        'type': child.type.spelling,
                        'ui_name': ui_name,
                    })

            elif child.kind == CX.CursorKind.CXX_METHOD:
                attrs = self._parse_annotation(child)
                if self._has_attr(attrs, 'Method'):
                    class_info['methods'].append({
                        'name': child.spelling,
                        'return_type': child.result_type.spelling,
                        'is_static': child.is_static_method(),
                        'is_const': child.is_const_method(),
                        'params': [arg.type.spelling for arg in child.get_arguments()],
                    })

        self._classes.append(class_info)

    def class_names(self) -> list:
        """Return list of class names that were collected."""
        return [cls['name'] for cls in self._classes]

    def has_classes(self) -> bool:
        """Return True if any meta-annotated classes were found."""
        return len(self._classes) > 0

    def generate(self, header_include: str = None) -> str:
        """Generate the registration .cpp file content (only per-class functions)."""
        if not self._classes:
            return ''

        lines = []
        lines.append('// Auto-generated by CS Meta Parser - DO NOT EDIT')
        lines.append('#include <UDRefl/ReflMngr.hpp>')
        lines.append('#include "scene/MetaTypeIndex.h"')
        if header_include:
            lines.append(f'#include "{header_include}"')
        lines.append('')

        for cls in self._classes:
            lines.append(f'// Registration for {cls["full_name"]}')
        lines.append('')

        for cls in self._classes:
            lines.append(self._generate_class_registration(cls))
            lines.append('')

        return '\n'.join(lines)

    @staticmethod
    def generate_aggregator(class_names: list) -> str:
        """Generate the aggregator .cpp that calls all Register_XXX functions."""
        lines = []
        lines.append('// Auto-generated by CS Meta Parser - DO NOT EDIT')
        lines.append('#include <UDRefl/ReflMngr.hpp>')
        lines.append('')
        lines.append('#ifdef _MSC_VER')
        lines.append('#define CS_META_EXPORT __declspec(dllexport)')
        lines.append('#else')
        lines.append(
            '#define CS_META_EXPORT __attribute__((visibility("default")))')
        lines.append('#endif')
        lines.append('')
        lines.append('namespace CS {')
        lines.append('')
        lines.append('// Forward declarations')
        for name in class_names:
            lines.append(f'void Register_{name}();')
        lines.append('')
        lines.append('void RegisterAllMetaTypes() {')
        for name in class_names:
            lines.append(f'    Register_{name}();')
        lines.append('}')
        lines.append('')
        lines.append('// Auto-register before main()')
        lines.append('#ifdef _MSC_VER')
        lines.append('#pragma init_seg(lib)')
        lines.append('#endif')
        lines.append('struct CS_META_EXPORT MetaAutoRegister {')
        lines.append('    MetaAutoRegister() { RegisterAllMetaTypes(); }')
        lines.append('};')
        lines.append('CS_META_EXPORT MetaAutoRegister g_metaAutoRegister;')
        lines.append('')
        lines.append('} // namespace CS')
        lines.append('')
        return '\n'.join(lines)

    def _generate_class_registration(self, cls) -> str:
        from collections import Counter
        indent = '    '
        class_name = cls['name']
        lines = []
        lines.append('namespace CS {')
        lines.append('')
        lines.append(f'void Register_{class_name}() {{')
        lines.append(f'{indent}using namespace Ubpa::UDRefl;')
        # NOTE: Do NOT use `Mngr` here. `Mngr` is an `inline static` reference
        # initialized during dynamic init of each TU. Per-class registration
        # TUs are not in `init_seg(lib)`, so their `Mngr` is uninitialized when
        # the aggregator (which IS in `init_seg(lib)`) invokes us pre-main.
        # Calling `ReflMngr::Instance()` (a Meyers' singleton) is always safe.
        lines.append(f'{indent}auto& mngr = ReflMngr::Instance();')
        lines.append('')

        lines.append(f'{indent}mngr.RegisterType(Ubpa::Type_of<{class_name}>, sizeof({class_name}), alignof({class_name}), std::is_polymorphic_v<{class_name}>, std::is_trivial_v<{class_name}>);')

        for base in cls['bases']:
            lines.append(
                f'{indent}mngr.AddBases<{class_name}, {base}>();')

        for field in cls['fields']:
            lines.append(
                f'{indent}// Field: {field["name"]} ({field["type"]})')
            lines.append(
                f'{indent}mngr.SimpleAddField<&{class_name}::{field["name"]}>("{field["ui_name"]}");')

        method_counts = Counter(m['name'] for m in cls['methods'])
        for method in cls['methods']:
            lines.append(f'{indent}// Method: {method["name"]}')
            if method['is_static']:
                lines.append(
                    f'{indent}mngr.AddMethod(Ubpa::Type_of<{class_name}>, "{method["name"]}", &{class_name}::{method["name"]});')
            elif method_counts[method['name']] > 1:
                # Overloaded method: use AddMemberMethod with explicit cast
                params = ', '.join(method['params'])
                const_qual = ' const' if method['is_const'] else ''
                ptr_type = f"{method['return_type']} ({class_name}::*)({params}){const_qual}"
                lines.append(
                    f'{indent}mngr.AddMemberMethod("{method["name"]}", static_cast<{ptr_type}>(&{class_name}::{method["name"]}));')
            else:
                lines.append(
                    f'{indent}mngr.AddMethod<&{class_name}::{method["name"]}>("{method["name"]}");')

        # Runtime bridge: register typeid -> Ubpa::Type so that domain
        # models can resolve a UDRefl Type from a polymorphic pointer.
        lines.append('')
        lines.append(
            f'{indent}CS::MetaTypeIndex::Register(typeid({class_name}), Ubpa::Type_of<{class_name}>);')

        lines.append('}')
        lines.append('')
        lines.append('} // namespace CS')
        return '\n'.join(lines)
